### ISSUE TITLE
[Colab 2026] error: module 'torchaudio' has no attribute 'AudioMetaData' (PyTorch 2.7.1 downgrade fix)

### ISSUE THREAD

**Issue by ubidragonPL** [DrewThomasson/ebook2audiobook#1677]
[colab_ebook2audiobook PyTorch 2.7.1 downgrade.ipynb](https://github.com/user-attachments/files/26166740/colab_ebook2audiobook.PyTorch.2.7.1.downgrade.ipynb)

Describe the bug
When running the notebook on Google Colab (March 2026, Python 3.12), the following three errors appear and completely block custom voice upload / XTTS cloning:

_detect_background() error: module 'torchaudio' has no attribute 'AudioMetaData'
→ Caused by torchaudio ≥ 2.9.0 removing the AudioMetaData class (breaking change in pyannote-audio 3.x type hints).
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.txt'
→ os.getcwd() is /content/ instead of /content/ebook2audiobook when importing lib.core / lib.conf.
KeyError: 'type' in show_alert(state) when uploading a custom voice file in Gradio
→ state is sometimes None or missing the 'type' key.

All three issues prevent successful custom speaker voice upload for XTTS cloning.
Environment

Google Colab (free tier, T4 GPU) – March 2026
Python 3.12
Pre-installed: torch==2.7.1, torchvision==0.22.1, torchaudio==2.7.1 (pinned)
pyannote-audio (from requirements.txt, 3.3.0–3.4.0)
gradio (from requirements.txt)

Fixes applied in the notebook (3 steps)
The patched notebook (ebook2audiobook_colab_fixed_2026.ipynb) is attached to this issue.
All old torch/torchaudio versions are removed and replaced with the exact compatible stack.
Step-by-step fix (replace these cells in your notebook):
Fix 1 – Force compatible torch/torchaudio stack (updated Step 1)

pip_commands = [
    ("pip uninstall -y torch torchvision torchaudio --quiet",
     "Remove all pre-installed conflicting Colab versions"),
    ("pip install -q torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 "
     "--index-url https://download.pytorch.org/whl/cu128",
     "Install exact compatible torch 2.7.1 + torchaudio 2.7.1 stack (fixes AudioMetaData error)"),
    ("pip install -q --upgrade pip setuptools wheel",
     "Upgrade pip / setuptools / wheel"),
    ("pip install -q --upgrade llvmlite numba --only-binary=:all:",
     "Install llvmlite & numba"),
    # local forks
    ("cd /content/ebook2audiobook && pip install -e ./ext/py/num2words --no-deps -q",
     "Install local num2words fork"),
    ("cd /content/ebook2audiobook && pip install -e ./ext/py/demucs --no-deps -q",
     "Install local demucs fork"),
    # clean requirements (skip ext/)
    ("cd /content/ebook2audiobook && grep -v '^ext/py/' requirements.txt > /tmp/clean_reqs.txt && "
     "pip install -q --upgrade --no-cache-dir -r /tmp/clean_reqs.txt",
     "Install clean Python requirements"),
    ("python -m unidic download",
     "Download Unidic dictionary"),
]

**Fix 2 – Patch pyannote.audio for torchaudio ≥ 2.9 (new Step 3.5 – insert right after Step 3)**

#Step 3.5 – Patch pyannote.audio (AudioMetaData → string reference)
print("\n--- Patching pyannote.audio (AudioMetaData → string reference) ---")
import glob, os
for pattern in [
    "/usr/local/lib/python3*/dist-packages/pyannote/audio/core/io.py",
    "/usr/local/lib/python3*/site-packages/pyannote/audio/core/io.py",
]:
    for path in glob.glob(pattern):
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                txt = f.read()
            if "torchaudio.AudioMetaData" in txt and '-> "torchaudio.AudioMetaData"' not in txt:
                txt = txt.replace("-> torchaudio.AudioMetaData:", '-> "torchaudio.AudioMetaData":')
                with open(path, "w", encoding="utf-8") as f:
                    f.write(txt)
                print("✅ Patched pyannote.audio/core/io.py")
            else:
                print("Patch was not needed / already applied")
            break
    else:
        continue
    break

**Fix 3 – Safe cwd + monkey-patch show_alert (insert after Step 5, before launching the app)**

#SAFE MONKEY-PATCH show_alert + fix cwd for VERSION.txt
print("\nApplying safe show_alert patch + fixing VERSION.txt path...")

import os
import gradio as gr

**Change working directory to repo root – fixes open('VERSION.txt')**
REPO_DIR = "/content/ebook2audiobook"
os.chdir(REPO_DIR)
print(f"✅ Changed current directory to: {os.getcwd()} (should be ebook2audiobook)")

**Safe import + monkey-patch**
try:
    from lib.core import show_alert as original_show_alert
    def patched_show_alert(state):
        if state is None or not isinstance(state, dict) or 'type' not in state:
            print("⚠️ Skipped KeyError 'type' in show_alert – returning empty alert")
            return gr.update(visible=False)
        try:
            return original_show_alert(state)
        except Exception as inner:
            print(f"Original show_alert error: {inner}")
            return gr.update(visible=False)
    
    # Overwrite globally
    import lib.core
    lib.core.show_alert = patched_show_alert
    
    print("✅ show_alert monkey-patch applied successfully")
except ImportError as imp_err:
    print(f"Import lib.core still fails: {imp_err}")
    print("   → Custom voice may not work. You can ignore it, it will work, I tested it.")

except Exception as e:
    print(f"Other error during patch: {e}")

After applying these three cells:

Background detection / Demucs / normalization works
Custom voice upload succeeds
XTTS cloning works (tested with Polish voice sample)

Suggested long-term improvements:

Add os.chdir(os.path.dirname(os.path.abspath(__file__))) at the top of app.py / lib/conf.py
Add guard clause in show_alert
Pin torchaudio<2.9 in requirements.txt or document Colab-specific torch stack

Thank you for the excellent project!

Attached file: ebook2audiobook_colab_fixed_2026.ipynb (fully patched notebook with all 3 fixes already applied).
You can now just replace the three sections above (or use the attached notebook) and everything works on Colab 2026. Enjoy!

[colab_ebook2audiobook PyTorch 2.7.1 downgrade.ipynb](https://github.com/user-attachments/files/26166718/colab_ebook2audiobook.PyTorch.2.7.1.downgrade.ipynb)

**Comment by ROBERT-MCDOWELL** [comment]
which colabs script did you use? ours never install torch 2.9.0. but always 2.7.1

**Comment by ubidragonPL** [comment]
> which colabs script did you use? ours never install torch 2.9.0. but always 2.7.1

used original official collab link to notebook from github linked https://colab.research.google.com/github/DrewThomasson/ebook2audiobook/blob/main/Notebooks/colab_ebook2audiobook.ipynb , ran into issues while upload voice to clone.  Gradio error "Warning
failed! Check if you audio file is compatible." console info: "nput file is valid
Convert to WAV...

Demux completed!
WAV conversion successful
Detecting if any background noise or music...
_detect_background() error: module 'torchaudio' has no attribute 'AudioMetaData'
_detect_background() error: module 'torchaudio' has no attribute 'AudioMetaData'
"   
or

"Input file is valid
Convert to WAV...

Demux completed!
WAV conversion successful
Detecting if any background noise or music...
_detect_background() error: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
_detect_background() error: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)"    colab is trying use torch==2.7.1 version.

**Comment by ROBERT-MCDOWELL** [comment]
I tested on my side and never had this kind of issue. are you using a GPU which one?
btw requirements don't install torchcodec as a final installation. at the end the E2A script installed the right versions.
something wrong happened during the installation. do  you still have the installation log?
E2A works with torch 2.7.1 nothing else.

**Comment by ubidragonPL** [comment]
> I tested on my side and never had this kind of issue. are you using a GPU which one? btw requirements don't install torchcodec as a final installation. at the end the E2A script installed the right versions. something wrong happened during the installation. do you still have the installation log? E2A works with torch 2.7.1 nothing else.

Tested on original colab notebook file with T4 free tier nvidia GPU. (Are there few different versions of collab notebooks?). I don't know what happened, run fresh install of original notebook, still got an error after upload audio file. Original runned code notebook and log in attachments.   I think its trying to use Torch 2.8.0+cu128 instead of Torch 2.7.1 , what can make conflicts.

[colab_ebook2audiobook.ipynb](https://github.com/user-attachments/files/26212652/colab_ebook2audiobook.ipynb)
[original log.txt](https://github.com/user-attachments/files/26212651/original.log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
some packages install automatically torch 2.8+, but at the end of the requirements torch 2.7.1+cu128 should be installed. I must check if I PR my version to the main branch and if our workflow is following it.

**Comment by ROBERT-MCDOWELL** [comment]
should be fixed. reopen if persists.

**Comment by ricardonevesmusic** [comment]
The first problem, might be that the Rust is failing to install, because it expects for E2A to already exist: the cloning of the E2A repo, only happen immediately after that and it should happen before it (or at least the location/path must exist or be created with some type of command).

`https://github.com/DrewThomasson/ebook2audiobook/commit/fe0b22304d7b0ea77be03af18da7f426c4366fc3#diff-103d14d890c08f584737c99c933165991ad044cd902452ff6837baac14b8c9e1L147`

`https://github.com/DrewThomasson/ebook2audiobook/commit/fe0b22304d7b0ea77be03af18da7f426c4366fc3#diff-103d14d890c08f584737c99c933165991ad044cd902452ff6837baac14b8c9e1R9-R147`

That's basically it.

**Comment by ROBERT-MCDOWELL** [comment]
this is an issue solved since long time and irrelevant now.
@ricardonevesmusic  what's your issue then?
